"""add chat session support

Revision ID: 091c3b306e21
Revises: 5f45e1b6d7a1
Create Date: 2026-03-30 18:32:14.459472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091c3b306e21'
down_revision: Union[str, Sequence[str], None] = '5f45e1b6d7a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Chat session title.'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Chat session creation date.'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_session_created_at'), 'chat_session', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_session_user_id'), 'chat_session', ['user_id'], unique=False)
    op.add_column('chat_history', sa.Column('session_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.create_foreign_key(None, 'chat_history', 'chat_session', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.drop_column('chat_history', 'session_id')
    op.drop_index(op.f('ix_chat_session_user_id'), table_name='chat_session')
    op.drop_index(op.f('ix_chat_session_created_at'), table_name='chat_session')
    op.drop_table('chat_session')
    # ### end Alembic commands ###
